# Generated by Django 4.1 on 2022-08-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=225)),
                ('post_name', models.CharField(max_length=225)),
                ('post_description', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'Posts',
            },
        ),
    ]
