# Generated by Django 4.1 on 2022-08-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
    ]
