# Generated by Django 4.1 on 2022-08-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_book_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
